- name: Delete a file.
  hosts: TEST 
  become: yes 
  tasks: 
    - name: delete a file 
      file:
        path: /tmp/1
        state: absent

    - name: delete a dir 
      file:
        path: /tmp/sample 
        state: absent


