- name: Check a file exists or not 
  hosts: TEST 
  tasks:
    - name: Check file exists 
      stat:
        path: /tmp/sample
      register: out 

    - debug: 
        msg: "{{out.stat.exists}}"

    - debug:
        msg: "Yes, File exists"
      when: out.stat.exists == true

    - debug:
        msg: "No, File not exists"
      when: out.stat.exists == false