- name: Lineinfile demo
  hosts: TEST 
  vars:
    DBHOST: sampledb
  tasks: 
    - name: Remove content in a file 
      lineinfile:
        path: /tmp/file1
        regexp: TestDB
        state: absent

    - name: update  content in a file 
      lineinfile:
        path: /tmp/file1
        insertbefore: "^</Context>$"
        line: '<Resource name="jdbc/TestDB" auth="Container" type="javax.sql.DataSource" maxActive="50" maxIdle="30" maxWait="10000" username="student" password="student@1" driverClassName="com.mysql.jdbc.Driver" url="jdbc:mysql://{{DBHOST}}:3306/studentapp"/>'
